// Source text of the generated dist/sw.js. Kept out of vite.config.ts so the service worker's
// behaviour can be unit-tested (serviceWorkerSource.test.ts runs it against fake caches/fetch).
// Framework- and DOM-free on purpose: vite.config.ts imports it under the node tsconfig.

export interface ServiceWorkerSourceInput {
  /** Short content hash of the build output; rolls the cache name on every deploy. */
  version: string;
  /** The app's base path, e.g. '/headroom/'. */
  base: string;
  /** Every built file to precache, as absolute paths under `base` (includes `${base}index.html`). */
  urls: string[];
}

export function serviceWorkerSource({ version, base, urls }: ServiceWorkerSourceInput): string {
  return `// Generated by vite.config.ts's serviceWorkerPlugin at build time. Do not edit by hand.
const CACHE_NAME = 'headroom-shell-${version}';
const BASE = ${JSON.stringify(base)};
const PRECACHE_URLS = ${JSON.stringify(urls)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_URLS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE_NAME && k.startsWith('headroom-shell-')).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

const INDEX_URL = \`\${BASE}index.html\`;

// Never touches a cross-origin request (in particular huggingface.co, which must always go
// straight to the network) or anything outside this app's own scope.
self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith(BASE)) return;

  // Navigations (a shared link's own URL, bare '/headroom/', a reload, ...) go network-first:
  // the whole calculator state lives in the query string, so there is no way to precache every
  // URL a shared link might use. Offline, fall back to the precached shell HTML itself (matched
  // by its own fixed URL, not the navigation's, so a never-seen '?...' still renders the app,
  // which then reads the query string once it boots).
  //
  // A navigation response is never written back over the cached shell: any same-scope URL can
  // be opened in a tab (manifest.webmanifest, og.png, a 200 error page...), and storing that as
  // index.html would make every offline visit serve it instead of the app. The shell only ever
  // comes from install-time precaching, which a new deploy refreshes by rolling CACHE_NAME.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).catch(() => caches.match(INDEX_URL, { ignoreVary: true }).then((cached) => cached ?? Response.error())),
    );
    return;
  }

  // Everything else (the built JS/CSS/icons): cache-first, topping up the cache with whatever
  // the network returns. ignoreVary: true because some static hosts (vite preview among them)
  // send 'Vary: Origin' on every response, and the browser's own Origin header on a live
  // same-origin 'cors' request (e.g. a module <script>) doesn't reliably match the header the
  // cache recorded for the identical URL when it was precached from inside the service worker —
  // a real Chromium quirk, not a hypothetical. We deliberately don't need content negotiation
  // for our own build output: each URL is one immutable, content-hashed file.
  event.respondWith(
    caches.match(req, { ignoreVary: true }).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(req, copy));
          }
          return res;
        })
        .catch(() => cached ?? Response.error());
    }),
  );
});
`;
}
